export const BookApi = [
    {
        image:"./image/book.jpg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: 100,
    },{
        image:"./image/book.jpg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: "100 Off",
    },{
        image:"./image/book.jpg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: "100 Off",
    },{
        image:"./image/book.jpg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: "100 Off",
    },{
        image:"./image/book.pg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: "100 Off",
    },{
        image:"./image/book.jpg",
        title:"Book Name",
        auther:"Auther Name",
        description :" book description",
        oldPrice: 50,
        newPrice: 150,
        offPrice: '100 Off',
    },
]